### ISSUE TITLE
isPlainObject method in utils seem doesn't work

### ISSUE THREAD

**Issue by YuZaiShui** [heyui/hey-utils#4]
let obj = {
    a: 'sa',
    b: {
        c: 15,
        d: function() {
            console.log(this);
        }
    }
};
isPlainObject(obj);  // true

**Comment by vvpvvp** [comment]
isPlainObject本来就是用来判断参数是否是一个纯粹的对象的，你是的示例是一个对象啊，请参考https://codeplayer.vip/p/j7sto
